<?php

/*
 * in this file you will find the configuration variables for the script
 */


return [
    /*
     * pass => is for the LeadOnly pages this has generated by password_hash function
     */
    "pass"=>'$2y$10$HZiMZ8b1uJittgrIOY05Muq6b04YlzCgWt7Tvua2YXkgWz3hZ/2.q'
];